name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: the-wright-engineer/codeserver/codeserver
          platforms: linux/amd64,linux/arm64
          context: .
          tag_with_ref: true
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
